### ISSUE TITLE
Docs on bluemix.net only Show a Spinner

### ISSUE THREAD

**Issue by broerse** [IBM-Bluemix/docs#1060]
https://console.ng.bluemix.net/docs/openwhisk/ Only shows a Spinner for more than 6 days. See also https://github.com/IBM-Bluemix/docs/pull/1038#event-935369021

**Comment by broerse** [comment]
Console Error I see:

```
GET https://ace-docs-production-20170119-185324.ng.bluemix.net/docs/api/content/openwhisk/?lang=nl-NL 404 (Not Found)
_request @ doc-content.html:2
get @ doc-content.html:2
setUrl @ doc-content.html:1
_urlChange @ doc-content.html:1
_observerEffect @ polymer.html:1656
_effectEffects @ polymer.html:1501
_propertySetter @ polymer.html:1485
setter @ polymer.html:1564
_setAttributeToProperty @ polymer-micro.html:631
_attributeChangedImpl @ polymer.html:2024
attributeChangedCallback @ polymer-micro.html:235
value @ docs.js:7
route @ docs.js:2
(anonymous) @ docs.js:2
value @ docs.js:3
(anonymous) @ docs.js:7
doc-content.html:1 Uncaught TypeError: Cannot read property 'errorPageTitle' of undefined
    at doc-content.html:1
    at XMLHttpRequest.s.onload (doc-content.html:2)
```

**Comment by jenschlot** [comment]
Hi Martin,
 
Can you provide some more details on which browser and OS you are using? When I go to that URL, I get a "Page Not Found" error because the actual URL for OpenWhisk is: https://console.ng.bluemix.net/docs/openwhisk/index.html
 
Also, how were you getting to that URL?
 
Thanks,Jenifer
 
Jenifer Schlotfeldt, Senior Content Strategist, Designer, Architect for IBM Bluemix Learn Experience
Email: jschlot@us.ibm.com
Phone: 720-395-5302 | T/L: 676-5302
 
 
----- Original message -----From: Martin Broerse <notifications@github.com>To: IBM-Bluemix/docs <docs@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [IBM-Bluemix/docs] Docs on bluemix.net only Show a Spinner (#1060)Date: Mon, Jan 30, 2017 11:51 PM 
Console Error I see:
GET https://ace-docs-production-20170119-185324.ng.bluemix.net/docs/api/content/openwhisk/?lang=nl-NL 404 (Not Found)_request @ doc-content.html:2get @ doc-content.html:2setUrl @ doc-content.html:1_urlChange @ doc-content.html:1_observerEffect @ polymer.html:1656_effectEffects @ polymer.html:1501_propertySetter @ polymer.html:1485setter @ polymer.html:1564_setAttributeToProperty @ polymer-micro.html:631_attributeChangedImpl @ polymer.html:2024attributeChangedCallback @ polymer-micro.html:235value @ docs.js:7route @ docs.js:2(anonymous) @ docs.js:2value @ docs.js:3(anonymous) @ docs.js:7doc-content.html:1 Uncaught TypeError: Cannot read property 'errorPageTitle' of undefined    at doc-content.html:1    at XMLHttpRequest.s.onload (doc-content.html:2)

**Comment by broerse** [comment]
I think I came from google. But https://console.ng.bluemix.net/docs/openwhisk/index.html also gives me the spinner. Perhaps it is some cdn error for the Netherlands.

**Comment by broerse** [comment]
It does not work on Chrome, Edge and Firefox on Windows 10

Chrome error:
```
Uncaught SyntaxError: Unexpected token <
bluemix-analytics.min.js:1 Page Event: Documentation, Documentation - docs
doc-content.html:1 Uncaught TypeError: Cannot read property 'lastUpdatedStr' of undefined
    at DetailPage._processVersion (doc-content.html:1)
    at DetailPage.value (doc-content.html:1)
    at DetailPage.value (doc-content.html:1)
    at new DetailPage (doc-content.html:1)
    at doc-content.html:1
    at XMLHttpRequest.s.onload (doc-content.html:2)
```

**Comment by broerse** [comment]
@jenschlot The docs on https://github.com/openwhisk/openwhisk/tree/master/docs work correct with .md links. Perhaps IBM can point to it while fixing the site.

**Comment by broerse** [comment]
@jenschlot It is working again. Thanks!

**Comment by jenschlot** [comment]
@broerse Great!
